# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_recipes_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='image',
        ),
    ]
