# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20190327_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hop_type', models.CharField(blank=True, choices=[('Admiral', 'Admiral'), ('Ahtanum', 'Ahtanum'), ('Amarillo', 'Amarillo'), ('Apollo', 'Apollo'), ('Bramling Cross', 'Bramling Cross'), ('Brewers Gold', 'Brewers Gold'), ('Bullion', 'Bullion'), ('Cascade', 'Cascade'), ('Centennial', 'Centennial'), ('Challenger', 'Challenger'), ('Chinook', 'Chinook'), ('Citra', 'Citra'), ('Cluster', 'Cluster'), ('Columbus', 'Columbus'), ('Crystal', 'Crystal'), ('Eroica', 'Eroica'), ('First Gold', 'First Gold'), ('Feux-Coeur', 'Feux-Coeur'), ('Fuggle', 'Fuggle'), ('Galaxy', 'Galaxy'), ('Galena', 'Galena'), ('Glacier', 'Glacier'), ('Goldings', 'Goldings'), ('Green Bullet', 'Green Bullet'), ('Greenburg', 'Greenburg'), ('Hallertau', 'Hallertau'), ('Herald', 'Herald'), ('Herkules', 'Herkules'), ('Hersbrucker', 'Hersbrucker'), ('Horizon', 'Horizon'), ('Liberty', 'Liberty'), ('Lublin', 'Lublin'), ('Magnum', 'Magnum'), ('Merkur', 'Merkur'), ('Millennium', 'Millennium'), ('Motueka', 'Motueka'), ('Mosaic', 'Mosaic'), ('Mount Hood', 'Mount Hood'), ('Mount Rainier', 'Mount Rainier'), ('Nelson Sauvin', 'Nelson Sauvin'), ('Newport', 'Newport'), ('Northdown', 'Northdown'), ('Northern Brewer', 'Northern Brewer'), ('Nugget', 'Nugget'), ('Opal', 'Opal'), ('Pacifica', 'Pacifica'), ('Pacific Gem', 'Pacific Gem'), ('Pacific Jade', 'Pacific Jade'), ('Palisade', 'Palisade'), ('Perle', 'Perle'), ('Phoenix', 'Phoenix'), ('Pilgrim', 'Pilgrim'), ('Pilot', 'Pilot'), ('Pioneer', 'Pioneer'), ('Polnischer', 'Polnischer'), ('Pride of Ringwood', 'Pride of Ringwood'), ('Progress', 'Progress'), ('Riwaka', 'Riwaka'), ('Saaz', 'Saaz'), ('Saaz Late', 'Saaz Late'), ('Bor', 'Bor'), ('Premiant', 'Premiant'), ('Rubin', 'Rubin'), ('Agnus', 'Agnus'), ('Vital', 'Vital'), ('Sladek', 'Sladek'), ('Kazbek', 'Kazbek'), ('Bohemie', 'Bohemie'), ('Harmonie', 'Harmonie'), ('San Juan Ruby Red', 'San Juan Ruby Red'), ('Santiam', 'Santiam'), ('Saphir', 'Saphir'), ('Satus', 'Satus'), ('Select', 'Select'), ('Simcoe', 'Simcoe'), ('Smaragd', 'Smaragd'), ('Sorachi Ace', 'Sorachi Ace'), ('Southern Cross', 'Southern Cross'), ('Spalt', 'Spalt'), ('Sterling', 'Sterling'), ('Strisselspalt', 'Strisselspalt'), ('Styrian Aurora', 'Styrian Aurora'), ('Styrian Bobek', 'Styrian Bobek'), ('Styrian Goldings', 'Styrian Goldings'), ('Styrian Celeia', 'Styrian Celeia'), ('Summit', 'Summit'), ('Tardif de Bourgogne', 'Tardif de Bourgogne'), ('Target', 'Target'), ('Taurus', 'Taurus'), ('Tettnang', 'Tettnang'), ('Tomahawk', 'Tomahawk'), ('Tomyski', 'Tomyski'), ('Tradition', 'Tradition'), ('Ultra', 'Ultra'), ('Vanguard', 'Vanguard'), ('Waimea', 'Waimea'), ('Warrior', 'Warrior'), ('Whitbread Golding Variety', 'Whitbread Golding Variety'), ('Willamette', 'Willamette'), ('Zeus', 'Zeus')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='hop_type',
        ),
    ]
