# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_hoptypes_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HopTypes',
            new_name='HopType',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
