# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20190329_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoptype',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='hop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hop', to='homepage.HopType'),
        ),
    ]
