# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20190329_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='final_gravity',
            new_name='final_gravity_sg',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='original_gravity',
            new_name='original_gravity_sg',
        ),
    ]
