# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20190329_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='final_gravity_plato',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='original_gravity_plato',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
